version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: buffer_suites_pg
    restart: always
    environment:
      POSTGRES_USER: buffer_user
      POSTGRES_PASSWORD: buffer_password
      POSTGRES_DB: buffer_suites
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
